name: CodeFlash

on:
  pull_request:
    paths:
      - "paperqa/**"
  workflow_dispatch:

concurrency: # Cancel prior if new push, SEE: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  optimize: # SEE: https://docs.codeflash.ai/getting-started/codeflash-github-actions
    runs-on: ubuntu-latest
    env:
      CODEFLASH_API_KEY: ${{ secrets.CODEFLASH_API_KEY }}
      CODEFLASH_PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Check if PR is from CodeFlash bot
        id: bot_check
        working-directory: .
        run: |
          echo "Checking if this PR is created by CodeFlash bot..."
          if [ "${{ github.event.pull_request.user.login }}" == "codeflash-ai[bot]" ]; then
            echo "PR created by Codeflash bot. Skipping optimization."
            echo "skip_remaining_steps=yes" >> $GITHUB_OUTPUT
          else
            echo "skip_remaining_steps=no" >> $GITHUB_OUTPUT
            echo "It's not. Proceeding with the optimization."
          fi
      - if: steps.bot_check.outputs.skip_remaining_steps == 'no'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: steps.bot_check.outputs.skip_remaining_steps == 'no'
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - if: steps.bot_check.outputs.skip_remaining_steps == 'no'
        run: uv sync
      - if: steps.bot_check.outputs.skip_remaining_steps == 'no'
        run: uv run codeflash
